/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.alumni.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-09-2013
 * 
 * XDoclet definition:
 * @struts.form name="customerForm"
 */
public class CustomerForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** email property */
	private String email;

	/** name property */
	private String name;

	/** mobileTel property */
	private String mobileTel;

	/** ID property */
	private Integer ID;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the email.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}

	/** 
	 * Set the email.
	 * @param email The email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/** 
	 * Returns the name.
	 * @return String
	 */
	public String getName() {
		return name;
	}

	/** 
	 * Set the name.
	 * @param name The name to set
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** 
	 * Returns the mobileTel.
	 * @return String
	 */
	public String getMobileTel() {
		return mobileTel;
	}

	/** 
	 * Set the mobileTel.
	 * @param mobileTel The mobileTel to set
	 */
	public void setMobileTel(String mobileTel) {
		this.mobileTel = mobileTel;
	}

	/** 
	 * Returns the ID.
	 * @return Integer
	 */
	public Integer getID() {
		return ID;
	}

	/** 
	 * Set the ID.
	 * @param ID The ID to set
	 */
	public void setID(Integer ID) {
		this.ID = ID;
	}
}