/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.alumni.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-10-2013
 * 
 * XDoclet definition:
 * @struts.form name="equipmentForm"
 */
@SuppressWarnings("serial")
public class EquipmentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** id property */
	private Integer id;

	/** usage property */
	private String eusage;

	/** date property */
	private String buy_time;

	/** type property */
	private String etype;
	
	private String ename;
	

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the id.
	 * @return Integer
	 */
	public Integer getId() {
		return id;
	}

	/** 
	 * Set the id.
	 * @param id The id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/** 
	 * Returns the end_time.
	 * @return String
	 */
	
	/** 
	 * Returns the usage.
	 * @return String
	 */
	public String getEusage() {
		return eusage;
	}

	/** 
	 * Set the usage.
	 * @param usage The usage to set
	 */
	public void setEusage(String eusage) {
		this.eusage = eusage;
	}

	/** 
	 * Returns the date.
	 * @return String
	 */

	/** 
	 * Returns the type.
	 * @return String
	 */
	public String getEtype() {
		return etype;
	}

	/** 
	 * Set the type.
	 * @param type The type to set
	 */
	public void setEtype(String etype) {
		this.etype = etype;
	}

	public void setBuy_time(String buy_time) {
		this.buy_time = buy_time;
	}

	public String getBuy_time() {
		return buy_time;
	}

	public void setEname(String ename) {
		this.ename = ename;
	}

	public String getEname() {
		return ename;
	}

}