/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.alumni.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 04-09-2013
 * 
 * XDoclet definition:
 * @struts.form name="sendMailForm"
 */
public class SendMailForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** content property */
	private String content;

	/** pwd property */
	private String pwd;

	/** title property */
	private String title;

	/** addressee property */
	private String addressee;

	/** adjunct property */
	private String adjunct;

	/** addresser property */
	private String addresser;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the content.
	 * @return String
	 */
	public String getContent() {
		return content;
	}

	/** 
	 * Set the content.
	 * @param content The content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/** 
	 * Returns the pwd.
	 * @return String
	 */
	public String getPwd() {
		return pwd;
	}

	/** 
	 * Set the pwd.
	 * @param pwd The pwd to set
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/** 
	 * Returns the title.
	 * @return String
	 */
	public String getTitle() {
		return title;
	}

	/** 
	 * Set the title.
	 * @param title The title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/** 
	 * Returns the addressee.
	 * @return String
	 */
	public String getAddressee() {
		return addressee;
	}

	/** 
	 * Set the addressee.
	 * @param addressee The addressee to set
	 */
	public void setAddressee(String addressee) {
		this.addressee = addressee;
	}

	/** 
	 * Returns the adjunct.
	 * @return String
	 */
	public String getAdjunct() {
		return adjunct;
	}

	/** 
	 * Set the adjunct.
	 * @param adjunct The adjunct to set
	 */
	public void setAdjunct(String adjunct) {
		this.adjunct = adjunct;
	}

	/** 
	 * Returns the addresser.
	 * @return String
	 */
	public String getAddresser() {
		return addresser;
	}

	/** 
	 * Set the addresser.
	 * @param addresser The addresser to set
	 */
	public void setAddresser(String addresser) {
		this.addresser = addresser;
	}
}