/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.alumni.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.alumni.struts.form.SendMailForm;
import com.alumni.core.ChStr;
import com.alumni.struts.dao.CustomerDAO;
import com.alumni.struts.dao.PersonnelDAO;
import com.alumni.struts.dao.SendMailDAO;

/** 
 * MyEclipse Struts
 * Creation date: 04-09-2013
 * 
 * XDoclet definition:
 * @struts.action path="/sendMail" name="sendMailForm" input="/mail/sendMail.jsp" scope="request" validate="true"
 */
public class SendMailAction extends Action {
	private SendMailDAO sendMailDAO = null;
    private PersonnelDAO personnelDAO=null;
    private CustomerDAO customerDAO=null;
    private ChStr chStr=new ChStr();
    public SendMailAction() {
        this.sendMailDAO = new SendMailDAO();
        this.personnelDAO=new PersonnelDAO();
        this.customerDAO=new CustomerDAO();
    }	
	public ActionForward execute(ActionMapping mapping,ActionForm form,HttpServletRequest request,HttpServletResponse response){
        String action = request.getParameter("action");
        if (action == null || "".equals(action)) {
            request.setAttribute("error","actionisnull");			
            return mapping.findForward("error");				
        }else if ("addMail".equals(action)) {
            return addMail(mapping, form, request,response);
        }else if("sendMail".equals(action)){
            return sendMail(mapping, form, request,response);
        }
			request.setAttribute("error", "action error");
			return mapping.findForward("error");
	}

    private ActionForward addMail(ActionMapping mapping, ActionForm form,
                              HttpServletRequest request,
                              HttpServletResponse response) {
        request.setAttribute("personnelQuery",personnelDAO.query(0));
        request.setAttribute("customerQuery",customerDAO.query(0));
        return mapping.findForward("addMail");
    }
    @SuppressWarnings("static-access")
	private ActionForward sendMail(ActionMapping mapping, ActionForm form,
                              HttpServletRequest request,
                              HttpServletResponse response){
        SendMailForm sendMailForm=(SendMailForm) form;
        sendMailForm.setTitle(chStr.toChinese(sendMailForm.getTitle()));
        sendMailForm.setAdjunct(chStr.toChinese(sendMailForm.getAdjunct()));
        sendMailForm.setContent(chStr.toChinese(sendMailForm.getContent()));
        sendMailForm.setPwd(sendMailForm.getPwd());
        int ret=sendMailDAO.sendMail(sendMailForm);
        System.out.println("password:"+sendMailForm.getPwd());
        if(ret==0){
            request.setAttribute("error","senderror");
            return mapping.findForward("error");
        }else{
            return mapping.findForward("sendMail");
        }
    }
}